assets:
- AMZN
- MSFT
- NVDA
- GLD
- USO
- IBM
- QBTS
- RGTI
- ACWI
- QUBT
- IONQ
- BNDX
cov_window: 20
indicators:
- name: rsi
  params:
    period: 14
- name: vola
  params:
    period: 60
- name: log
- name: volume_change
lookback_window: 20
n_assets: 12
paths:
  plots: analysis/plots
  processed: data/processed
  raw: data/raw
  scalers: data/processed/scalers
records_number_threshold: 1000
start_year: 2015
train_size: 0.7
use_past_cov_in_features: true
use_past_ret_in_features: true
